/**
 * compile.ts — TS module → JS function body compiler.
 *
 * Pipeline:
 *   1. Strip TypeScript types (via node:module)
 *   2. Parse as ES module with acorn
 *   3. Walk acorn AST, emit JS function body:
 *      - imports  → `const fn = getNoteSync("#hash")` (local-local)
 *      - remote(importedName, arg)  → `remote("#hash", arg)` (local-server)
 *      - exports  → strip keyword, return the single exported function
 *   4. Append `return exportedName;`
 *
 * Constraint: each file exports exactly one function.
 * All output is generated by walking the AST — no string slicing.
 */

import { parse as acornParse } from "acorn";
import { stripTypeScriptTypes } from "node:module";

// Acorn AST node — we use a loose type since acorn's types are complex
type N = { type: string; start: number; end: number; [k: string]: any };

// ---------------------------------------------------------------------------
// Minimal JS emitter for acorn AST
// ---------------------------------------------------------------------------

/**
 * Emit an expression node to JS string.
 * `importHashes` maps imported names → their hash strings. When we see
 * `remote(importedName, arg)`, we replace the imported name with its hash.
 */
const emit = (node: N, importHashes?: Map<string, string>): string => {
  switch (node.type) {
    case "Identifier":
      return node.name;
    case "Literal":
      return node.raw ?? JSON.stringify(node.value);
    case "TemplateLiteral": {
      const qs: string[] = node.quasis.map((q: N) => q.value.raw);
      const exprs: string[] = node.expressions.map((e: N) => emit(e, importHashes));
      let out = "`";
      for (let i = 0; i < qs.length; i++) {
        out += qs[i];
        if (i < exprs.length) out += "${" + exprs[i] + "}";
      }
      return out + "`";
    }
    case "TaggedTemplateExpression":
      return emit(node.tag, importHashes) + emit(node.quasi, importHashes);
    case "ArrayExpression":
      return "[" + (node.elements as N[]).map((e: N) => e ? emit(e, importHashes) : "").join(", ") + "]";
    case "ObjectExpression":
      return "({" + (node.properties as N[]).map(n => emitPropOrSpread(n, importHashes)).join(", ") + "})";
    case "Property": {
      if (node.shorthand) return emit(node.key, importHashes);
      if (node.computed) return "[" + emit(node.key, importHashes) + "]: " + emit(node.value, importHashes);
      return emit(node.key, importHashes) + ": " + emit(node.value, importHashes);
    }
    case "SpreadElement":
      return "..." + emit(node.argument, importHashes);
    case "UnaryExpression":
      return node.prefix
        ? (node.operator === "typeof" || node.operator === "void" || node.operator === "delete"
            ? node.operator + " " + emit(node.argument, importHashes)
            : node.operator + emit(node.argument, importHashes))
        : emit(node.argument, importHashes) + node.operator;
    case "BinaryExpression":
    case "LogicalExpression":
      return "(" + emit(node.left, importHashes) + " " + node.operator + " " + emit(node.right, importHashes) + ")";
    case "AssignmentExpression":
      return emit(node.left, importHashes) + " " + node.operator + " " + emit(node.right, importHashes);
    case "UpdateExpression":
      return node.prefix ? node.operator + emit(node.argument, importHashes) : emit(node.argument, importHashes) + node.operator;
    case "ConditionalExpression":
      return "(" + emit(node.test, importHashes) + " ? " + emit(node.consequent, importHashes) + " : " + emit(node.alternate, importHashes) + ")";
    case "MemberExpression":
      if (node.computed) return emit(node.object, importHashes) + "[" + emit(node.property, importHashes) + "]";
      if (node.optional) return emit(node.object, importHashes) + "?." + emit(node.property, importHashes);
      return emit(node.object, importHashes) + "." + emit(node.property, importHashes);
    case "CallExpression":
    case "NewExpression": {
      // Compile-time rewrite: remote(importedName, arg) → remote("#hash", arg)
      if (
        importHashes &&
        node.type === "CallExpression" &&
        node.callee.type === "Identifier" &&
        node.callee.name === "remote" &&
        node.arguments.length >= 1
      ) {
        const firstArg = node.arguments[0] as N;
        if (firstArg.type === "Identifier" && importHashes.has(firstArg.name)) {
          const hash = importHashes.get(firstArg.name)!;
          const restArgs = (node.arguments as N[]).slice(1).map(a => emit(a, importHashes));
          const allArgs = [JSON.stringify(hash), ...restArgs].join(", ");
          return "remote(" + allArgs + ")";
        }
      }
      const prefix = node.type === "NewExpression" ? "new " : "";
      const callee = emit(node.callee, importHashes);
      const args = (node.arguments as N[]).map(a => emit(a, importHashes)).join(", ");
      const opt = node.optional ? "?." : "";
      return prefix + callee + opt + "(" + args + ")";
    }
    case "SequenceExpression":
      return "(" + (node.expressions as N[]).map(e => emit(e, importHashes)).join(", ") + ")";
    case "ArrowFunctionExpression": {
      const async = node.async ? "async " : "";
      const params = (node.params as N[]).map(emitPattern).join(", ");
      const body = node.body.type === "BlockStatement" ? emitBlock(node.body, importHashes) : emit(node.body, importHashes);
      return async + "(" + params + ") => " + body;
    }
    case "FunctionExpression": {
      const async = node.async ? "async " : "";
      const name = node.id ? " " + node.id.name : "";
      const params = (node.params as N[]).map(emitPattern).join(", ");
      return async + "function" + name + "(" + params + ") " + emitBlock(node.body, importHashes);
    }
    case "YieldExpression":
      return node.delegate ? "yield* " + emit(node.argument, importHashes) : "yield " + (node.argument ? emit(node.argument, importHashes) : "");
    case "AwaitExpression":
      return "await " + emit(node.argument, importHashes);
    case "ThisExpression":
      return "this";
    case "ChainExpression":
      return emit(node.expression, importHashes);
    default:
      throw new Error("emit: unsupported expression " + node.type);
  }
};

const emitPropOrSpread = (node: N, importHashes?: Map<string, string>): string => {
  if (node.type === "SpreadElement") return "..." + emit(node.argument, importHashes);
  return emit(node, importHashes);
};

const emitPattern = (p: N): string => {
  switch (p.type) {
    case "Identifier":
      return p.name;
    case "AssignmentPattern":
      return emitPattern(p.left) + " = " + emit(p.right);
    case "RestElement":
      return "..." + emitPattern(p.argument);
    case "ArrayPattern":
      return "[" + (p.elements as (N | null)[]).map(e => e ? emitPattern(e) : "").join(", ") + "]";
    case "ObjectPattern":
      return "{" + (p.properties as N[]).map(pp => {
        if (pp.type === "RestElement") return "..." + emitPattern(pp.argument);
        if (pp.shorthand) return emitPattern(pp.value);
        if (pp.computed) return "[" + emit(pp.key) + "]: " + emitPattern(pp.value);
        return emit(pp.key) + ": " + emitPattern(pp.value);
      }).join(", ") + "}";
    default:
      throw new Error("emitPattern: unsupported " + p.type);
  }
};

const emitBlock = (block: N, importHashes?: Map<string, string>): string => {
  return "{\n" + (block.body as N[]).map(s => emitStmt(s, importHashes)).join("\n") + "\n}";
};

const emitStmt = (s: N, importHashes?: Map<string, string>): string => {
  switch (s.type) {
    case "BlockStatement":
      return emitBlock(s, importHashes);
    case "ExpressionStatement":
      return emit(s.expression, importHashes) + ";";
    case "VariableDeclaration":
      return emitVarDecl(s, importHashes);
    case "ReturnStatement":
      return "return" + (s.argument ? " " + emit(s.argument, importHashes) : "") + ";";
    case "IfStatement": {
      let out = "if (" + emit(s.test, importHashes) + ") " + emitStmt(s.consequent, importHashes);
      if (s.alternate) out += " else " + emitStmt(s.alternate, importHashes);
      return out;
    }
    case "ForStatement": {
      const init = s.init ? (s.init.type === "VariableDeclaration" ? emitVarDeclRaw(s.init, importHashes) : emit(s.init, importHashes)) : "";
      const test = s.test ? emit(s.test, importHashes) : "";
      const update = s.update ? emit(s.update, importHashes) : "";
      return "for (" + init + "; " + test + "; " + update + ") " + emitStmt(s.body, importHashes);
    }
    case "ForInStatement": {
      const left = s.left.type === "VariableDeclaration" ? emitVarDeclRaw(s.left, importHashes) : emit(s.left, importHashes);
      return "for (" + left + " in " + emit(s.right, importHashes) + ") " + emitStmt(s.body, importHashes);
    }
    case "ForOfStatement": {
      const left = s.left.type === "VariableDeclaration" ? emitVarDeclRaw(s.left, importHashes) : emit(s.left, importHashes);
      const aw = s.await ? "await " : "";
      return "for " + aw + "(" + left + " of " + emit(s.right, importHashes) + ") " + emitStmt(s.body, importHashes);
    }
    case "WhileStatement":
      return "while (" + emit(s.test, importHashes) + ") " + emitStmt(s.body, importHashes);
    case "DoWhileStatement":
      return "do " + emitStmt(s.body, importHashes) + " while (" + emit(s.test, importHashes) + ");";
    case "BreakStatement":
      return "break" + (s.label ? " " + s.label.name : "") + ";";
    case "ContinueStatement":
      return "continue" + (s.label ? " " + s.label.name : "") + ";";
    case "ThrowStatement":
      return "throw " + emit(s.argument, importHashes) + ";";
    case "TryStatement": {
      let out = "try " + emitBlock(s.block, importHashes);
      if (s.handler) {
        const param = s.handler.param ? "(" + emitPattern(s.handler.param) + ") " : " ";
        out += " catch " + param + emitBlock(s.handler.body, importHashes);
      }
      if (s.finalizer) out += " finally " + emitBlock(s.finalizer, importHashes);
      return out;
    }
    case "SwitchStatement": {
      let out = "switch (" + emit(s.discriminant, importHashes) + ") {\n";
      for (const c of s.cases as N[]) {
        out += c.test ? "case " + emit(c.test, importHashes) + ":\n" : "default:\n";
        for (const cs of c.consequent as N[]) out += emitStmt(cs, importHashes) + "\n";
      }
      return out + "}";
    }
    case "LabeledStatement":
      return s.label.name + ": " + emitStmt(s.body, importHashes);
    case "FunctionDeclaration": {
      const async = s.async ? "async " : "";
      const gen = s.generator ? "*" : "";
      const name = s.id ? s.id.name : "";
      const params = (s.params as N[]).map(emitPattern).join(", ");
      return async + "function " + gen + name + "(" + params + ") " + emitBlock(s.body, importHashes);
    }
    case "EmptyStatement":
      return "";
    default:
      throw new Error("emitStmt: unsupported " + s.type);
  }
};

const emitVarDecl = (v: N, importHashes?: Map<string, string>): string => emitVarDeclRaw(v, importHashes) + ";";
const emitVarDeclRaw = (v: N, importHashes?: Map<string, string>): string => {
  const decls = (v.declarations as N[]).map(d => {
    const id = emitPattern(d.id);
    return d.init ? id + " = " + emit(d.init, importHashes) : id;
  });
  return v.kind + " " + decls.join(", ");
};

// ---------------------------------------------------------------------------
// Strip types
// ---------------------------------------------------------------------------

/**
 * Strip TypeScript types from a function body source (no import/export).
 * Wraps in an async function to allow top-level return/await, then unwraps.
 */
export const stripTypes = (tsSrc: string): string => {
  const wrapped = `async function __wrap__() {\n${tsSrc}\n}`;
  const stripped = stripTypeScriptTypes(wrapped, { mode: "strip" });
  const open = stripped.indexOf("{\n") + 2;
  const close = stripped.lastIndexOf("\n}");
  return stripped.slice(open, close);
};

// ---------------------------------------------------------------------------
// Module compiler
// ---------------------------------------------------------------------------

export type ResolveResult =
  | string                     // hash string — local import via getNoteSync
  | { hash: string; mode: "local" }   // explicit local
  | { hash: string; mode: "remote" }; // explicit remote (unused for now, remote is detected at call sites)

const resolveHash = (rr: ResolveResult): string =>
  typeof rr === "string" ? rr : rr.hash;

/**
 * Compile a TS module source to a JS function body.
 *
 * Each file must export exactly one function. Imports are resolved to hashes:
 * - Local usage: `const fn = getNoteSync("#hash")` — synchronous cached lookup
 * - remote() calls: `remote(fn, arg)` → `remote("#hash", arg)` — compile-time rewrite
 *
 * @param tsSrc   TypeScript module source
 * @param resolve Maps import specifiers → hash strings
 */
export const compileModule = (
  tsSrc: string,
  resolve?: (specifier: string) => ResolveResult,
): string => {
  // 1. Strip types
  const jsSrc = stripTypeScriptTypes(tsSrc, { mode: "strip" });

  // 2. Parse as module
  const ast = acornParse(jsSrc, {
    ecmaVersion: "latest",
    sourceType: "module",
  }) as unknown as N;

  // 3. First pass: collect imports into importHashes (no emit yet)
  const importHashes = new Map<string, string>();
  const sideEffectHashes: string[] = []; // imports with no specifiers
  const nonImportNodes: N[] = [];

  for (const node of ast.body as N[]) {
    if (node.type === "ImportDeclaration") {
      const specs = node.specifiers as N[];
      if (specs.length === 0) {
        // Side-effect import: import "#setup"
        const raw: string = node.source.value;
        const rr = resolve ? resolve(raw) : raw;
        sideEffectHashes.push(resolveHash(rr));
      } else {
        collectImport(node, importHashes, resolve);
      }
    } else {
      nonImportNodes.push(node);
    }
  }

  // 4. Scan non-import AST to find which imported names are used locally
  //    (i.e. not just as remote() first arg)
  const locallyUsed = findLocalUses(nonImportNodes, importHashes);

  // 5. Emit getNoteSync bindings only for locally-used imports
  const lines: string[] = [];
  for (const hash of sideEffectHashes) {
    lines.push(`getNoteSync(${JSON.stringify(hash)});`);
  }
  for (const [name, hash] of importHashes) {
    if (locallyUsed.has(name)) {
      lines.push(`const ${name} = getNoteSync(${JSON.stringify(hash)});`);
    }
  }

  // 6. Walk non-import statements, emit JS
  const exportNames: string[] = [];

  for (const node of nonImportNodes) {
    switch (node.type) {
      case "ExportNamedDeclaration":
        emitNamedExport(node, lines, exportNames, importHashes, resolve);
        break;

      case "ExportDefaultDeclaration":
        emitDefaultExport(node, lines, exportNames, importHashes);
        break;

      case "ExportAllDeclaration":
        throw new Error("export * from '...' is not supported");

      default:
        lines.push(emitStmt(node, importHashes));
        break;
    }
  }

  // 7. Emit __deps preamble — unique hashes of all imports (including side-effect)
  const depHashes = [...new Set([...sideEffectHashes, ...importHashes.values()])];
  if (depHashes.length > 0) {
    const depsLine = "const __deps = [" + depHashes.map(h => JSON.stringify(h)).join(", ") + "];";
    lines.unshift(depsLine);
  }

  // 8. Return the exported function
  if (exportNames.length === 1) {
    const name = exportNames[0] === "default" ? "__default" : exportNames[0];
    lines.push("return " + name + ";");
  } else if (exportNames.length > 1) {
    const parts = exportNames.map(n =>
      n === "default" ? "default: __default" : n
    );
    lines.push("return {" + parts.join(", ") + "};");
  }

  return lines.join("\n") + "\n";
};

// ---------------------------------------------------------------------------
// Import emission
// ---------------------------------------------------------------------------

/** Register imported names → hash (no line emission). */
const collectImport = (
  node: N,
  importHashes: Map<string, string>,
  resolve?: (s: string) => ResolveResult,
) => {
  const raw: string = node.source.value;
  const rr = resolve ? resolve(raw) : raw;
  const hash = resolveHash(rr);
  const specs = node.specifiers as N[];

  for (const s of specs) {
    importHashes.set(s.local.name, hash);
  }
};

/**
 * Walk AST nodes and find imported names that are used locally
 * (i.e. anywhere except as the first argument to remote()).
 */
const findLocalUses = (nodes: N[], importHashes: Map<string, string>): Set<string> => {
  const used = new Set<string>();

  const walkExpr = (e: N, insideRemoteFirstArg = false): void => {
    if (!e) return;
    switch (e.type) {
      case "Identifier":
        if (!insideRemoteFirstArg && importHashes.has(e.name)) {
          used.add(e.name);
        }
        return;
      case "Literal": return;
      case "CallExpression":
      case "NewExpression": {
        // For remote(importedName, ...) — skip the first arg
        const isRemote = e.type === "CallExpression"
          && e.callee.type === "Identifier"
          && e.callee.name === "remote"
          && e.arguments.length >= 1;
        if (isRemote) {
          walkExpr(e.arguments[0], true); // first arg: don't count as local use
          for (let i = 1; i < (e.arguments as N[]).length; i++) walkExpr(e.arguments[i]);
          // Don't walk callee — "remote" itself isn't an import
        } else {
          walkExpr(e.callee);
          for (const a of (e.arguments || []) as N[]) walkExpr(a);
        }
        return;
      }
      case "ArrowFunctionExpression":
        for (const p of (e.params || []) as N[]) walkPattern(p);
        if (e.body.type === "BlockStatement") walkBlock(e.body);
        else walkExpr(e.body);
        return;
      case "FunctionExpression":
        for (const p of (e.params || []) as N[]) walkPattern(p);
        walkBlock(e.body);
        return;
      case "MemberExpression":
        walkExpr(e.object);
        if (e.computed) walkExpr(e.property);
        return;
      case "BinaryExpression": case "LogicalExpression":
        walkExpr(e.left); walkExpr(e.right); return;
      case "AssignmentExpression":
        walkExpr(e.left); walkExpr(e.right); return;
      case "UnaryExpression": case "UpdateExpression":
        walkExpr(e.argument); return;
      case "ConditionalExpression":
        walkExpr(e.test); walkExpr(e.consequent); walkExpr(e.alternate); return;
      case "SequenceExpression":
        for (const x of (e.expressions || []) as N[]) walkExpr(x); return;
      case "ArrayExpression":
        for (const x of (e.elements || []) as N[]) if (x) walkExpr(x); return;
      case "ObjectExpression":
        for (const p of (e.properties || []) as N[]) {
          if (p.type === "SpreadElement") walkExpr(p.argument);
          else { if (p.computed) walkExpr(p.key); walkExpr(p.value); }
        }
        return;
      case "SpreadElement": walkExpr(e.argument); return;
      case "TemplateLiteral":
        for (const x of (e.expressions || []) as N[]) walkExpr(x); return;
      case "TaggedTemplateExpression":
        walkExpr(e.tag); walkExpr(e.quasi); return;
      case "AwaitExpression": case "YieldExpression":
        if (e.argument) walkExpr(e.argument); return;
      case "ChainExpression": walkExpr(e.expression); return;
      case "ThisExpression": return;
    }
  };

  const walkPattern = (_p: N): void => { /* patterns don't reference imports */ };

  const walkStmt = (s: N): void => {
    if (!s) return;
    switch (s.type) {
      case "ExpressionStatement": walkExpr(s.expression); return;
      case "VariableDeclaration":
        for (const d of (s.declarations || []) as N[]) {
          if (d.init) walkExpr(d.init);
        }
        return;
      case "ReturnStatement": case "ThrowStatement":
        if (s.argument) walkExpr(s.argument); return;
      case "IfStatement":
        walkExpr(s.test); walkStmt(s.consequent);
        if (s.alternate) walkStmt(s.alternate); return;
      case "BlockStatement": walkBlock(s); return;
      case "ForStatement":
        if (s.init) { if (s.init.type === "VariableDeclaration") walkStmt(s.init); else walkExpr(s.init); }
        if (s.test) walkExpr(s.test);
        if (s.update) walkExpr(s.update);
        walkStmt(s.body); return;
      case "ForInStatement": case "ForOfStatement":
        if (s.left.type === "VariableDeclaration") walkStmt(s.left); else walkExpr(s.left);
        walkExpr(s.right); walkStmt(s.body); return;
      case "WhileStatement": case "DoWhileStatement":
        walkExpr(s.test); walkStmt(s.body); return;
      case "TryStatement":
        walkBlock(s.block);
        if (s.handler) walkBlock(s.handler.body);
        if (s.finalizer) walkBlock(s.finalizer); return;
      case "SwitchStatement":
        walkExpr(s.discriminant);
        for (const c of (s.cases || []) as N[]) {
          if (c.test) walkExpr(c.test);
          for (const cs of (c.consequent || []) as N[]) walkStmt(cs);
        }
        return;
      case "FunctionDeclaration":
        walkBlock(s.body); return;
      case "LabeledStatement": walkStmt(s.body); return;
      case "BreakStatement": case "ContinueStatement": case "EmptyStatement": return;
    }
  };

  const walkBlock = (block: N) => {
    for (const s of (block.body || []) as N[]) walkStmt(s);
  };

  // Walk the top-level nodes (exports unwrap their declarations)
  for (const node of nodes) {
    if (node.type === "ExportNamedDeclaration") {
      if (node.declaration) walkStmt(node.declaration);
    } else if (node.type === "ExportDefaultDeclaration") {
      walkExpr(node.declaration);
    } else {
      walkStmt(node);
    }
  }

  return used;
};

// ---------------------------------------------------------------------------
// Export emission
// ---------------------------------------------------------------------------

const emitNamedExport = (
  node: N,
  lines: string[],
  exportNames: string[],
  importHashes: Map<string, string>,
  resolve?: (s: string) => ResolveResult,
) => {
  const decl = node.declaration as N | null;

  if (decl) {
    if (decl.type === "VariableDeclaration") {
      for (const d of decl.declarations as N[]) {
        const names = collectPatternNames(d.id);
        exportNames.push(...names);
        const id = emitPattern(d.id);
        lines.push(decl.kind + " " + id + (d.init ? " = " + emit(d.init, importHashes) : "") + ";");
      }
    } else if (decl.type === "FunctionDeclaration") {
      exportNames.push(decl.id.name);
      lines.push(emitStmt(decl, importHashes));
    }
    return;
  }

  // export { a, b } or export { a } from "#hash"
  const specifiers = node.specifiers as N[];
  const source = node.source as N | null;

  if (source) {
    const raw: string = source.value;
    const rr = resolve ? resolve(raw) : raw;
    const hash = resolveHash(rr);
    const bindings = specifiers.map((s: N) => {
      const exported: string = s.exported.name;
      exportNames.push(exported);
      return exported;
    });
    // Re-export from another module — fetch it
    if (bindings.length === 1) {
      lines.push(`const ${bindings[0]} = getNoteSync(${JSON.stringify(hash)});`);
    } else {
      const parts = specifiers.map((s: N) => {
        const local: string = s.local.name;
        const exported: string = s.exported.name;
        return local === exported ? local : local + ": " + exported;
      });
      lines.push(`const {${parts.join(", ")}} = getNoteSync(${JSON.stringify(hash)});`);
    }
  } else {
    // export { a, b } — just collect names
    for (const s of specifiers) {
      exportNames.push(s.exported.name);
    }
  }
};

const emitDefaultExport = (
  node: N,
  lines: string[],
  exportNames: string[],
  importHashes: Map<string, string>,
) => {
  exportNames.push("default");
  const decl = node.declaration as N;
  lines.push("const __default = " + emit(decl, importHashes) + ";");
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const collectPatternNames = (node: N): string[] => {
  const names: string[] = [];
  const walk = (n: N) => {
    switch (n.type) {
      case "Identifier": names.push(n.name); break;
      case "ObjectPattern":
        for (const p of n.properties as N[]) {
          if (p.type === "RestElement") walk(p.argument);
          else walk(p.value);
        }
        break;
      case "ArrayPattern":
        for (const e of n.elements as (N | null)[]) if (e) walk(e);
        break;
      case "RestElement": walk(n.argument); break;
      case "AssignmentPattern": walk(n.left); break;
    }
  };
  walk(node);
  return names;
};
